/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:36b5cfcf-3f16-477d-9b97-f5b380a85d14",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_UohYTuSF7",
    "aws_user_pools_web_client_id": "iijmri71ratu7blijflfqoe9n",
    "oauth": {}
};


export default awsmobile;
